---
- name: Install Docker and Docker Compose, and deploy from Git
  hosts: all  ## play against all hosts defined in hosts file
  become: yes

  vars_files:
    - vault.yml

  tasks:
    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      retries: 3
      delay: 10
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        - python3-pip

    - name: Install GPG on Ubuntu
      become: yes  # Run the task with elevated privileges
      apt:
        name: gnupg
        state: present

    # - name: Add Docker GPG key
    #   ansible.builtin.apt_key:
    #     url: https://download.docker.com/linux/ubuntu/gpg
    #     state: present

    # - name: Add Docker APT repository
    #   apt_repository:
    #     repo: deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    #     state: present
    #     validate_certs: false

    - name: Download Docker GPG key
      shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg --batch --yes"

    - name: Add Docker repository
      shell: >
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" |
        tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: Update apt repositories
      apt:
        update_cache: yes
      retries: 3
      delay: 10


    - name: Install Docker
      apt:
        update_cache: yes
        name: docker-ce
        state: present
      retries: 3
      delay: 10


    - name: Install Docker Compose
      pip:
        name: docker-compose
        state: present

    # - name: Clone or pull the Git repository
    #   git:
    #     repo: https://github.com/your_username/your_docker_compose_repo.git
    #     dest: /path/to/your/local/repo

    - name: Clone or pull the Git repository from self-hosted GitLab with basic auth
      git:
        repo: "https://{{ gitlab_username }}:{{ gitlab_password }}@git.netall.live/devops/nexus.git"
        dest: /opt/nexus
        accept_hostkey: yes  # Add this line if you're using SSH and need to accept the host key


    - name: Deploy Docker Compose
      command: docker compose up -d
      args:
        chdir: /opt/nexus

